name: Deploy PR Preview to GitHub Pages
on:
  pull_request:
    types:
      - opened
      - synchronize

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: preview-${{ github.ref }}
  cancel-in-progress: false

jobs:
  deploy-pr-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install
        run: npm install

      - name: Build
        run: npm run build

      - name: Unzip
        working-directory: dist/apps
        run: find -name '*.zip' -exec sh -c 'unzip -d "${1%_[0-9.]*.zip}" "$1"' _ {} \;

      - name: Cleanup
        working-directory: dist/apps
        run: rm *.zip

      - name: Deploy to GitHub Pages
        uses: rossjrw/pr-preview-action@v1
        with:
          action: deploy
          source-dir: dist/apps
